import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | AI Fitness Coach",
    default: "AI Fitness Coach - Your Personal Workout & Diet Planner",
  },
  description: "Get a personalized 7-day workout and diet plan generated by AI. Tailored to your goals, fitness level, and preferences.",
  applicationName: "AI Fitness Coach",
  keywords: ["Fitness", "AI", "Workout Plan", "Diet Plan", "Health", "Gym", "Home Workout"],
  authors: [{ name: "gsamansharma" }],
  creator: "AI Fitness Coach",
  manifest: "/manifest.json", 
  icons: {
    icon: "/favicon.ico",
    apple: "/icons/apple-touch-icon.png", 
  },
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
